In [ ]:
import numpy as np

data = np.array([78,7,45,67,34,56,89,43])
###  the array slicing array (Positive)
data[0 : 4]
print(data[4 : 6])
# data[2] ## 45

[34 56]


In [6]:
import numpy as np

data = np.array([12,23,45,78,7,45,67,34])
### Getting value from the array (Negative)
print(data[-7 : -2])
print(data[-5 :])
data[::-1] 

[23 45 78  7 45]
[78  7 45 67 34]


array([34, 67, 45,  7, 78, 45, 23, 12])